# Visualisation using HepRep and JAS

/control/verbose 0
/run/verbose 0
/vis/verbose 2
/tracking/verbose 0
#/stepping/verbose 3
/vis/scene/create

# Visualization
  /vis/scene/create kon.bheprep
  /vis/open HepRepXML
  /vis/drawVolume
  /vis/viewer/flush
  /vis/scene/add/trajectories
  /vis/scene/add/hits
  /tracking/storeTrajectory 1
  /vis/scene/endOfEventAction accumulate

# Histograms
#******************
/analysis/h1/set 3 100 0 5 MeV
/analysis/setFileName Spec_KON
 
# Run
 /run/beamOn 1

