# Visualisation using OpenGL

/control/verbose 0
/run/verbose 0
/vis/verbose 2
/tracking/verbose 0
#/stepping/verbose 3
/vis/scene/create

/vis/open
#/vis/open ATree
#/vis/open VRML2FILE
#/vis/open DAWNFILE
#/vis/open HepRepFile
#/vis/open RayTracer

/vis/viewer/set/viewpointThetaPhi 270 0 deg
/vis/scene/add/trajectories
/vis/viewer/set/style w

/tracking/storeTrajectory 2
/vis/scene/endOfEventAction accumulate
/gun/position -15 0 0
/gun/momentum 1 1 0
/gun/energy 0.2 MeV

# Run
/run/beamOn 1